FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi==0.111.0 uvicorn==0.30.1 \
    optimum[onnxruntime]==1.19.0 transformers==4.41.2 pydantic==2.7.1

COPY onnx_model/ ./onnx_model/
COPY app_onnx.py .

EXPOSE 8001
CMD ["uvicorn", "app_onnx:app", "--host", "0.0.0.0", "--port", "8001"]
